### ISSUE TITLE
MIssing FIle 

### ISSUE THREAD

**Issue by sebk95** [Broukmiken/Nginx.exe-32-and-64-bits-With-RTMP#1]
Hi,
you didn't have upload streaming server tool folder.
Plese upload this folder. I can't complete your tutorial.

Thanks for great job

**Comment by sebk95** [comment]
founded in all files

**Comment by Broukmiken** [comment]
yes, it's in " Files.for.streaming.zip " archive
https://github.com/Broukmiken/Nginx.exe-32-and-64-bits-With-RTMP/releases/latest
