### ISSUE TITLE
Low Latency

### ISSUE THREAD

**Issue by Scro-mx** [Broukmiken/Nginx.exe-32-and-64-bits-With-RTMP#2]
Hello, I would like to contact you, because I would like to know if it is possible to reduce the latency of the stream viewing? I currently have a latency of between 15 and 20 seconds and I'd like to reduce it.

Sincerely

**Comment by Scro-mx** [comment]
Because I'd like to retrieve a person's stream to share it back in OBS so that I can share the 2 screens on the same stream without too much latency!

**Comment by Broukmiken** [comment]
Hello,
You should use srt stream or whip stream.
It's very low latency streams protocol (0.5s)
You then have to forget nginx and use Mediamtx instead.
It's a great free media server, have a look on github.

Cheers
